'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const testFile=path.join(process.cwd(),'data','test.json'); process.env.DATA_FILE=testFile; process.env.ADMIN_TOKEN='test-secret'; try{fs.unlinkSync(testFile)}catch{}
const {server,aiReply}=require('../src/server'); let base; test.before(async()=>await new Promise(r=>server.listen(0,()=>{base=`http://127.0.0.1:${server.address().port}`;r()})));test.after(()=>server.close());
const proof='data:image/png;base64,iVBORw0KGgo='; const makeOrder=(itemId,location='Dodoma')=>({itemId,customer:{fullName:'Amina Test',phone:'0712345678',whatsapp:'255712345678'},child:{name:'Mwana',age:4},delivery:location==='Other Region'?{location,region:'Mwanza',district:'Ilemela',busCompany:'Other Bus',station:'Nyegezi',recipientName:'Amina',recipientPhone:'0712345678'}:{location,method:'Pickup',area:'Emaus',address:'Emaus'},paymentProof:proof});
test('catalogue and bilingual safe AI replies work',async()=>{let r=await fetch(base+'/api/catalog');let x=await r.json();assert.equal(x.products.length,5);assert.match(aiReply('bei ni gani','sw'),/Bei/);assert.match(aiReply('what is the price','en'),/Prices/);});
test('product order saves pending payment and sequential number',async()=>{let r=await fetch(base+'/api/orders',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(makeOrder('zaminocal'))});let x=await r.json();assert.equal(r.status,201);assert.equal(x.order.id,'NTI-0001');assert.equal(x.order.paymentStatus,'PENDING');});
test('package/other-region order saves and admin can mark paid',async()=>{let r=await fetch(base+'/api/orders',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(makeOrder('package-1','Other Region'))});let x=await r.json();assert.equal(x.order.id,'NTI-0002');r=await fetch(base+'/api/admin/orders/NTI-0002',{method:'PATCH',headers:{'content-type':'application/json',authorization:'Bearer test-secret'},body:JSON.stringify({paymentStatus:'PAID'})});x=await r.json();assert.equal(x.order.paymentStatus,'PAID');assert.equal(x.order.amount,250000);assert.equal(x.notification.delivered,false);});
test('assessment, appointment and handoff persist',async()=>{let r=await fetch(base+'/api/assessments',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({age:3,concern:'sleep',sleep:'concern'})});assert.equal(r.status,201);r=await fetch(base+'/api/appointments',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({parentName:'A',phone:'7',childName:'B',age:3,concern:'C',location:'Dodoma',date:'2026-09-14',time:'08:00'})});assert.equal(r.status,201);r=await fetch(base+'/api/ai',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({question:'a unique unclear issue',language:'en'})});let x=await r.json();assert.equal(x.handoff,true);});
