'use strict';
const http = require('node:http'); const fs = require('node:fs'); const path = require('node:path'); const crypto = require('node:crypto');
const { read, mutate, newOrder } = require('./store');
const PORT = Number(process.env.PORT || 3000); const ADMIN_TOKEN = process.env.ADMIN_TOKEN || 'change-me-before-production';
const business = { name: 'NeuroTotoInsight', phone: '0792 237 454', whatsapp: '+255759237454', email: 'neurototoinsight@gmail.com', locations: ['Dodoma', 'Dar es Salaam'], paymentNumber: '52255746', paymentName: 'ABBYFAR SHOP' };
function send(res, status, body, type='application/json') { res.writeHead(status, {'Content-Type':type, 'Cache-Control':'no-store'}); res.end(type === 'application/json' ? JSON.stringify(body) : body); }
function body(req) { return new Promise((resolve,reject) => { let s=''; req.on('data',c=>{ s+=c; if(s.length>8e6) reject(Error('Payload too large')); }); req.on('end',()=>{try{resolve(s?JSON.parse(s):{});}catch{reject(Error('Invalid JSON'));}}); }); }
function admin(req) { return req.headers.authorization === `Bearer ${ADMIN_TOKEN}`; }
function orderValidation(o, catalog) { const item = [...catalog.products,...catalog.packages].find(x=>x.id===o.itemId); if(!item || !o.customer?.fullName || !o.customer?.phone || !o.customer?.whatsapp || !o.child?.name || o.child?.age === undefined || !o.delivery?.location || !o.paymentProof) return null; if(!['Dodoma','Dar es Salaam','Other Region'].includes(o.delivery.location)) return null; if(o.delivery.location === 'Other Region' && (!o.delivery.region || !o.delivery.district || !o.delivery.busCompany || !o.delivery.station || !o.delivery.recipientName || !o.delivery.recipientPhone)) return null; if(o.delivery.location !== 'Other Region' && (!o.delivery.method || !o.delivery.area || !o.delivery.address)) return null; return item; }
async function notifyWhatsApp(message, to) { const token=process.env.WHATSAPP_TOKEN, phoneId=process.env.WHATSAPP_PHONE_NUMBER_ID; if(!token || !phoneId || !to) return { delivered:false, reason:'WhatsApp Cloud API is not configured' }; const r=await fetch(`https://graph.facebook.com/v20.0/${phoneId}/messages`, {method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({messaging_product:'whatsapp',to:to.replace(/\D/g,''),type:'text',text:{body:message}})}); if(!r.ok) throw Error(`WhatsApp delivery failed: ${r.status}`); return {delivered:true}; }
function handoff(text, language='sw') { const contact=`WhatsApp: +255 759 237 454 | ${business.phone} | ${business.email}`; return language==='en' ? `This question needs NeuroTotoInsight support. Please contact us directly. ${contact}` : `Swali hili linahitaji msaada wa NeuroTotoInsight. Tafadhali wasiliana nasi moja kwa moja. ${contact}`; }
function aiReply(question, language) { const q=question.toLowerCase(); const urgent=/(trouble breathing|unconscious|seizure|bleeding|can't drink|cannot drink|kupumua kwa shida|degedege|hajitambui|kutokwa damu)/.test(q); if(urgent) return language==='en' ? 'Seek urgent medical care now or call local emergency services. This service cannot assess an emergency.' : 'Tafadhali tafuta huduma ya dharura ya matibabu sasa au piga huduma za dharura za eneo lako. Huduma hii haiwezi kutathmini dharura.';
 if(/price|bei|cost/.test(q)) return language==='en' ? 'Prices: Zaminocal TZS 90,000; Cerebrain TZS 120,000; Vitamin C TZS 90,000; Yunzhi TZS 130,000; Anatic Soap TZS 15,000.' : 'Bei: Zaminocal TZS 90,000; Cerebrain TZS 120,000; Vitamin C TZS 90,000; Yunzhi TZS 130,000; Anatic Soap TZS 15,000.';
 if(/order|agiza|delivery|delivery|usafirishaji/.test(q)) return language==='en' ? 'Use Place order to provide delivery details and upload payment proof. Payment stays pending until an administrator verifies it.' : 'Tumia Agiza kutoa maelezo ya usafirishaji na kupakia uthibitisho wa malipo. Malipo hubaki PENDING hadi msimamizi ayathibitishe.';
 return null; }
const server=http.createServer(async(req,res)=>{ try { const url=new URL(req.url, `http://${req.headers.host}`); const route=url.pathname; if(req.method==='GET' && route==='/api/config') return send(res,200,{business, whatsappConfigured:Boolean(process.env.WHATSAPP_TOKEN&&process.env.WHATSAPP_PHONE_NUMBER_ID)});
 if(req.method==='GET' && route==='/api/catalog') { const d=read(); return send(res,200,{products:d.products,packages:d.packages,regions:d.regions,busCompanies:d.busCompanies}); }
 if(req.method==='POST' && route==='/api/orders') { const input=await body(req), catalog=read(), item=orderValidation(input,catalog); if(!item) return send(res,400,{error:'Complete all mandatory order, delivery, and payment-proof fields.'}); const proof=input.paymentProof; if(!/^data:image\/(png|jpeg|webp);base64,/.test(proof)) return send(res,400,{error:'Payment proof must be a PNG, JPEG, or WebP image.'}); const ext=proof.match(/^data:image\/(png|jpeg|webp)/)[1].replace('jpeg','jpg'); const proofName=`${crypto.randomUUID()}.${ext}`; fs.mkdirSync('uploads',{recursive:true}); fs.writeFileSync(path.join('uploads',proofName),Buffer.from(proof.split(',')[1],'base64')); const order=newOrder({itemId:item.id,itemName:item.name,amount:item.price,customer:input.customer,child:input.child,delivery:input.delivery,paymentProof:`/uploads/${proofName}`}); return send(res,201,{order}); }
 if(req.method==='POST' && route==='/api/assessments') { const x=await body(req); if(!x.age || !x.concern) return send(res,400,{error:'Age and main concern are required.'}); const red=/breathing|seizure|unconscious|bleeding|kupumua|degedege|hajitambui|damu/i.test(JSON.stringify(x)); const result={summary:'Educational screening only; it is not a diagnosis.', areas:[x.concern, ...(x.sleep==='concern' ? ['Sleep'] : []), ...(x.eating==='concern' ? ['Eating'] : [])], redFlag:red, guidance:red?'Seek urgent professional medical care now.':'Observe development, offer varied age-appropriate food, and discuss ongoing concerns with a qualified clinician.'}; mutate(d=>d.assessments.push({...x,id:crypto.randomUUID(),result,createdAt:new Date().toISOString()})); return send(res,201,{result}); }
 if(req.method==='POST' && route==='/api/appointments') { const x=await body(req); if(!x.parentName||!x.phone||!x.childName||!x.age||!x.concern||!x.location||!x.date||!x.time) return send(res,400,{error:'Complete all appointment fields.'}); const dt=new Date(`${x.date}T${x.time}`), day=dt.getDay(), hour=dt.getHours()+dt.getMinutes()/60; const ranges={0:[5,11],1:[2.5,13],2:[2.5,13],3:[2.5,13],4:[2.5,13],5:[3,23.5]}; if(!ranges[day]||hour<ranges[day][0]||hour>ranges[day][1]) return send(res,400,{error:'Preferred time is outside published working hours.'}); const a=mutate(d=>{const a={...x,id:crypto.randomUUID(),status:'REQUESTED',createdAt:new Date().toISOString()};d.appointments.push(a);return a;}); return send(res,201,{appointment:a}); }
 if(req.method==='POST' && route==='/api/ai') { const x=await body(req), language=x.language==='en'?'en':'sw', answer=aiReply(String(x.question||''),language); if(!x.question) return send(res,400,{error:'Question is required.'}); if(!answer) mutate(d=>d.handoffs.push({id:crypto.randomUUID(),question:x.question,language,status:'OPEN',createdAt:new Date().toISOString()})); return send(res,200,{answer:answer||handoff(x.question,language),handoff:!answer}); }
 if(req.method==='GET' && route==='/api/admin/data') { if(!admin(req)) return send(res,401,{error:'Unauthorized'}); return send(res,200,read()); }
 if(/^\/api\/admin\/(products|packages|busCompanies|regions)$/.test(route) && ['POST','PATCH','DELETE'].includes(req.method)) { if(!admin(req)) return send(res,401,{error:'Unauthorized'}); const collection=route.split('/').pop(), x=await body(req); let result; mutate(d=>{ const list=d[collection]; if(req.method==='POST'){ if(!x || (collection==='products'||collection==='packages')&&!x.id) throw Error('Record id is required'); result=collection==='products'||collection==='packages'?{...x}:String(x.name||x); list.push(result); } else { const i=list.findIndex(v=>typeof v==='string'?v===x.id:v.id===x.id); if(i<0) throw Error('Record not found'); if(req.method==='DELETE') result=list.splice(i,1)[0]; else result=list[i]=typeof list[i]==='string'?String(x.name):{...list[i],...x}; } }); return send(res,200,{record:result}); }
 if(req.method==='PATCH' && /^\/api\/admin\/orders\/NTI-\d+$/.test(route)) { if(!admin(req)) return send(res,401,{error:'Unauthorized'}); const x=await body(req); if(!['PENDING','PAYMENT VERIFIED','PAID','COMPLETED'].includes(x.paymentStatus)) return send(res,400,{error:'Invalid status'}); let order; mutate(d=>{order=d.orders.find(o=>o.id===route.split('/').pop());if(order){order.paymentStatus=x.paymentStatus;if(x.paymentStatus==='PAID')order.paidAt=new Date().toISOString();}}); if(!order)return send(res,404,{error:'Order not found'}); let notification={delivered:false}; if(x.paymentStatus==='PAID') { const m=`🔔 PAYMENT CONFIRMED — ORDER PAID\n\nOrder: ${order.id}\nProduct/Package: ${order.itemName}\nAmount Paid: TZS ${order.amount}\nCustomer: ${order.customer.fullName}\nPhone: ${order.customer.phone}\nChild: ${order.child.name}\nAge: ${order.child.age}\nLocation: ${order.delivery.location}\nDelivery: ${order.delivery.method||order.delivery.region}\nBus Company: ${order.delivery.busCompany||'-'}\nBus Station: ${order.delivery.station||'-'}\nPayment Status: PAID`; notification=await notifyWhatsApp(m,process.env.ADMIN_WHATSAPP); } return send(res,200,{order,notification}); }
 if(req.method==='POST' && route==='/webhooks/whatsapp') { const x=await body(req); const text=x.text||''; const language=/\b(bei|agiza|habari|mtoto|naomba|nini)\b/i.test(text)?'sw':'en'; const answer=aiReply(text,language)||handoff(text,language); mutate(d=>d.conversations.push({id:crypto.randomUUID(),incoming:x,answer,createdAt:new Date().toISOString()})); return send(res,202,{received:true,answer,delivery:'Webhook stores and returns reply; configure WhatsApp Cloud API webhook delivery to send messages.'}); }
 if(req.method==='GET' && (route==='/'||route==='/app.js'||route==='/style.css'||route.startsWith('/uploads/'))) { const f=route==='/'?'public/index.html':route.startsWith('/uploads/')?route.slice(1):`public${route}`; const ext=path.extname(f); const types={'.html':'text/html','.js':'text/javascript','.css':'text/css','.png':'image/png','.jpg':'image/jpeg','.webp':'image/webp'}; if(!fs.existsSync(f))return send(res,404,'Not found','text/plain');return send(res,200,fs.readFileSync(f),types[ext]||'application/octet-stream'); }
 return send(res,404,{error:'Not found'}); } catch(e){return send(res,400,{error:e.message});} });
if(require.main===module) server.listen(PORT,()=>console.log(`NeuroTotoInsight running on http://localhost:${PORT}`)); module.exports={server,aiReply,orderValidation};
